// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteEducation(arg1) {
  return window['go']['main']['App']['DeleteEducation'](arg1);
}

export function DeleteExperience(arg1) {
  return window['go']['main']['App']['DeleteExperience'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ExportDOCX() {
  return window['go']['main']['App']['ExportDOCX']();
}

export function ExportPDF(arg1) {
  return window['go']['main']['App']['ExportPDF'](arg1);
}

export function ExportPDFFromData(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExportPDFFromData'](arg1, arg2, arg3, arg4, arg5);
}

export function GetEducation() {
  return window['go']['main']['App']['GetEducation']();
}

export function GetExperiences() {
  return window['go']['main']['App']['GetExperiences']();
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportResume() {
  return window['go']['main']['App']['ImportResume']();
}

export function SaveEducation(arg1) {
  return window['go']['main']['App']['SaveEducation'](arg1);
}

export function SaveExperience(arg1) {
  return window['go']['main']['App']['SaveExperience'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectPhoto() {
  return window['go']['main']['App']['SelectPhoto']();
}
