// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {parser} from '../models';

export function DeleteEducation(arg1:number):Promise<void>;

export function DeleteExperience(arg1:number):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function ExportDOCX():Promise<void>;

export function ExportPDF(arg1:string):Promise<void>;

export function ExportPDFFromData(arg1:models.Profile,arg2:Array<models.Education>,arg3:Array<models.Experience>,arg4:Array<models.Project>,arg5:string):Promise<void>;

export function GetEducation():Promise<Array<models.Education>>;

export function GetExperiences():Promise<Array<models.Experience>>;

export function GetProfile():Promise<models.Profile>;

export function GetProjects():Promise<Array<models.Project>>;

export function GetSettings():Promise<models.Settings>;

export function ImportResume():Promise<parser.ExtractedData>;

export function SaveEducation(arg1:models.Education):Promise<void>;

export function SaveExperience(arg1:models.Experience):Promise<void>;

export function SaveProfile(arg1:models.Profile):Promise<void>;

export function SaveProject(arg1:models.Project):Promise<void>;

export function SaveSettings(arg1:models.Settings):Promise<void>;

export function SelectPhoto():Promise<string>;
